server.port: 8080
spring:
  applicaton:
    name: admin
  cloud:
    kubernetes:
      discovery:
        all-namespaces: false
        include-not-ready-addresses: true
        service-labels:
          spring-boot: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
