#kind: Namespace
#apiVersion: v1
#metadata:
#  name: n-1
#  labels:
#    name: n-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-1-config
  namespace: n-1
data:
  client-1-config.json:
    '{
      "server.port": 8080,
      "spring.application.name": "sba-client-1-from-config-map",
      "greeting": "Hello World from client-1-config.yml"
    }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-1
  namespace: n-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-1
  template:
    metadata:
      labels:
        app: client-1
    spec:
      containers:
        - name: client-1
          image: sba-client-1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: client-1-config
                  key: client-1-config.json
---
apiVersion: v1
kind: Service
metadata:
  name: client-1
  namespace: n-1
  labels:
    app: SBAClient-1
    spring-boot: "true"
spec:
  type: NodePort
  selector:
    app: client-1
  ports:
    - port: 8080
      targetPort: 8080